[2025-04-23T12:25:10.868+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-23T12:25:10.880+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:25:03.351967+00:00 [queued]>
[2025-04-23T12:25:10.886+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:25:03.351967+00:00 [queued]>
[2025-04-23T12:25:10.887+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-23T12:25:10.893+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_preprocessing> on 2025-04-23 12:25:03.351967+00:00
[2025-04-23T12:25:10.901+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=120) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T12:25:10.902+0000] {standard_task_runner.py:63} INFO - Started process 122 to run task
[2025-04-23T12:25:10.903+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_pipeline', 'run_preprocessing', 'manual__2025-04-23T12:25:03.351967+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocessing.py', '--cfg-path', '/tmp/tmp_aahnhy9']
[2025-04-23T12:25:10.904+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask run_preprocessing
[2025-04-23T12:25:10.945+0000] {task_command.py:426} INFO - Running <TaskInstance: preprocessing_pipeline.run_preprocessing manual__2025-04-23T12:25:03.351967+00:00 [running]> on host b1b997bb6fef
[2025-04-23T12:25:11.003+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocessing_pipeline' AIRFLOW_CTX_TASK_ID='run_preprocessing' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T12:25:03.351967+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T12:25:03.351967+00:00'
[2025-04-23T12:25:11.004+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-23T12:25:11.004+0000] {dag_preprocessing.py:95} INFO - Esecuzione del task di preprocessing iniziata.
[2025-04-23T12:25:11.004+0000] {dag_preprocessing.py:30} INFO - Avvio del preprocessing dei dati...
[2025-04-23T12:25:11.004+0000] {dag_preprocessing.py:34} INFO - Percorso previsto per il CSV: /opt/***/sentiment_data/all-data.csv
[2025-04-23T12:25:11.005+0000] {dag_preprocessing.py:37} INFO - Caricamento del file CSV...
[2025-04-23T12:25:11.031+0000] {dag_preprocessing.py:39} INFO - File CSV caricato correttamente, numero di righe: 4846
[2025-04-23T12:25:11.033+0000] {dag_preprocessing.py:51} INFO - Strumenti di preprocessamento inizializzati.
[2025-04-23T12:25:11.034+0000] {dag_preprocessing.py:69} INFO - Inizio preprocessamento del testo...
[2025-04-23T12:25:11.037+0000] {dag_preprocessing.py:73} ERROR - Errore durante il preprocessamento: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T12:25:11.038+0000] {dag_preprocessing.py:100} ERROR - Errore nel task di preprocessing: 
**********************************************************************
  Resource [93mpunkt_tab[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt_tab')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt_tab/english/[0m

  Searched in:
    - '/home/***/nltk_data'
    - '/home/***/.local/nltk_data'
    - '/home/***/.local/share/nltk_data'
    - '/home/***/.local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/opt/***/nltk_data'
**********************************************************************

[2025-04-23T12:25:11.038+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-23T12:25:11.038+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-23T12:25:11.042+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=preprocessing_pipeline, task_id=run_preprocessing, run_id=manual__2025-04-23T12:25:03.351967+00:00, execution_date=20250423T122503, start_date=20250423T122510, end_date=20250423T122511
[2025-04-23T12:25:11.087+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-23T12:25:11.099+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T12:25:11.100+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
